import Head from 'next/head'
import { Cart } from '../components/cart'
import { Products } from '../components/products'
import { CartProvider } from '../context/cart'
import { CatalogProvider } from '../context/catalog'
import { CurrencyContext, CurrencyProvider } from '../context/currency'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.columns}>
          <CurrencyProvider>
            <CatalogProvider>
              <CartProvider>
                <Products />

                <Cart />
              </CartProvider>
            </CatalogProvider>
          </CurrencyProvider>
        </div>
      </main>
    </div>
  )
}
